"""Curated TaxKraft scope vocabulary + embedding anchors.

Every term below is grounded in the knowledge_base/ seed corpus. Keeping this list
explicit (rather than learned) makes the guardrail auditable and easy to extend.
"""

# term (regex, lowercased) -> positive weight
SCOPE_TERMS = {
    r"\btaxkraft\b": 3.0,
    r"\btax\s*kraft\b": 3.0,
    r"\bgst\b": 1.5,
    r"gstin": 2.0,
    r"gst\s*registration": 1.0,
    r"gst\s*return": 1.0,
    r"gstr": 2.0,
    r"gst\s*notice": 1.0,
    r"e[\s-]?commerce\s*(seller|operator)?\s*gst": 1.0,
    r"\brcm\b|letter of undertaking|\blut\b": 1.0,
    r"gst\s*filing": 1.0,
    r"\bitr\b|income ?tax\s*(return|filing)": 1.5,
    r"income ?tax": 1.0,
    r"\bitr-?\d|sahaj|sugam": 1.5,
    r"\btds\b|\btcs\b": 1.5,
    r"tds ?return": 1.0,
    r"tax ?assessment|income ?tax ?notice|intimation": 1.0,
    r"12a|80g|80-?iac|fcra|15ca|15cb": 1.2,
    r"private limited|pvt\s*ltd|\bpvtd": 1.5,
    r"public limited": 1.5,
    r"\bllp\b|limited liability partnership": 1.5,
    r"one ?person ?company|\bopc\b": 1.5,
    r"partnership\s*(firm)?": 1.2,
    r"section\s*8": 1.5,
    r"sole proprietorship|proprietorship": 1.2,
    r"startup india": 1.5,
    r"company\s*registration|incorporat": 1.2,
    r"director|din|dsc|share capital|moa|aod?" : 0.6,
    r"trademark": 1.5,
    r"msme|udyam": 1.5,
    r"fssai|food\s*license": 1.5,
    r"\biec\b|import[\s-]?export": 1.2,
    r"\biso\b|bis\b|isi mark|\blei\b": 1.2,
    r"\bgem\b|government\s*e-marketplace": 1.2,
    r"shop and establishment|shops? & estab": 1.2,
    r"\bpf\b|provident\s*fund|epf|esic|\besi\b": 1.2,
    r"\bpan\b(?!agram)|permanent account number|\btan\b": 1.2,
    r"annual\s*compliance|ro\s*c\b|mca\s*filing|roc\s*filing": 1.5,
    r"compliance": 0.8,
    r"cfo\s*servic|due diligence": 1.5,
    r"project\s*report|detailed project report": 1.5,
    r"business\s*loan|working capital|term\s*loan|retail\s*loan": 1.5,
    r"loan": 0.8,
    r"tax\s*saving|advisory|cashflow|forecast": 0.8,
    r"bookkeeping|accounting\s*servic|payroll": 0.8,
    r"chartered\s*accountant|\bca\b(?!nada)\s*(firm|expert|services)?": 1.0,
    r"tax\s*expert": 0.8,
    r"\bpricing\b|\bfee\b|\bcost\b|\bprice\b": 0.8,
    r"how\s*much": 0.5,
    r"book\s*a|schedule\s*a|consultation": 0.6,
    r"process|how\s*it\s*works|how\s*do\s*i\s*(start|begin|register|file)": 0.6,
    r"document": 0.4,
    r"reminder|deadline|due date": 0.6,
    r"contact|phone|email|call|whatsapp": 0.8,
    r"office|address|noida|location|visit": 0.8,
    r"support|help\s*(me|with)?|customer\s*care": 0.6,
    r"book\s*a\s*ca|talk\s*to\s*(a\s*)?(ca|expert|human)": 1.0,
    r"partner|reseller|affiliate|become\s*partner": 1.0,
    r"service|services": 0.6,
    r"about\s*taxkraft|company\s*profile": 1.0,
    r"gst\s*cancellation|cancel\s*my\s*gst": 1.2,
    r"gst\s*modif": 1.2,
}

# negative-signal terms that flip a query toward OFF-SCOPE (weights are penalties)
OFF_TOPIC_TERMS = {
    r"cleartax|tally\s*solutions|boxoffice|equa|myca\b|gstportail|legaldev|taxcaller|onecall": 3.0,
    r"vs\s+\w+": 1.5,
    r"compare\s+\w+\s+(and|vs|with)": 1.5,
    r"recipe|food\s*to\s*make|how\s*to\s*cook": 2.0,
    r"movie|film|netflix|bollywood|hollywood": 2.0,
    r"politics|politician|election|government\s*policy|modi|party": 2.0,
    r"weather|rain|temperature|forecast": 2.0,
    r"sports|cricket|ipl|football|match": 2.0,
    r"health|medical|disease|symptom|doctor|hospital": 2.0,
    r"game|gaming|chess|pubg": 2.0,
    r"singapore|america|uk\s*tax|us\s*tax|canada\s*tax": 1.5,
    r"pakistan|china\s*tax": 1.5,
    r"religion|caste|god": 2.0,
    r"invest\s*in\s*(stocks|mutual|crypto)|bitcoin|stock\s*market\s*tips": 1.2,
    r"virgin|nude|sex|porn": 2.0,
    r"violent|kill|weapon|bomb": 2.0,
    r"\bjoke\b|\bpoem\b|\bstory\b|\bsong\b|\blyrics\b": 2.0,
    r"best\s*phone|best\s*laptop|iphone|android": 1.5,
    r"homework|assignment|essay": 1.5,
}

# Anchor statements whose embeddings define the PRODUCTION scope centroid.
EMBEDDING_ANCHORS = [
    "TaxKraft is a CA firm in India offering GST registration and monthly, quarterly and annual GST return filing services",
    "TaxKraft helps with income tax return (ITR) filing through expert Chartered Accountants in India",
    "TaxKraft provides company registration services: private limited, LLP, OPC, partnership, section 8, sole proprietorship and Startup India",
    "TaxKraft offers trademark, MSME, Udyam, FSSAI, IEC, ISO, GEM, shop and establishment, PF, ESI, PAN, TAN, DSC, BIS, ISI and LEI registrations",
    "TaxKraft handles ROC compliance and annual compliance for private limited companies, LLPs and partnership firms",
    "TaxKraft provides CFO services, due diligence, project reports and business loan support for SMEs",
    "TaxKraft assists with GST notices and income tax notice responses and assessments",
    "TaxKraft contact details: phone +91-8608601620, email info@taxkraft.com, office in Noida, Uttar Pradesh, India",
    "TaxKraft pricing and process: zero hidden fees, human support from expert CAs, timely reminders and year-round consultation",
    "TaxKraft partner program, service catalog and blogs for startups, individuals and small businesses across India",
    "TaxKraft tax-saving strategies, cashflow and business advisory for growth",
]